name: friend_app
description: "Friend cross-platform social app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_ui: ^0.0.1
  cross_cache: ^1.1.1
  dio: ^5.9.0
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  image: ^4.5.2
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  share_plus: ^10.1.4
  tinode: ^1.0.0-alpha.4
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.2
  flutter_chat_core: ^2.9.1
  flutter_chat_ui: ^2.12.0
  flutter_dotenv: ^6.0.0
  flutter_link_previewer: ^4.2.1
  flutter_lorem: ^2.0.0
  flyer_chat_audio_message: ^0.0.13+1
  flyer_chat_custom_message: ^0.0.13+1
  flyer_chat_file_message: ^2.4.1
  flyer_chat_image_message: ^2.3.1
  flyer_chat_location_message: ^0.0.13+1
  flyer_chat_system_message: ^2.2.1
  flyer_chat_text_message: ^2.6.1
  flyer_chat_text_stream_message: ^2.3.1
  flyer_chat_video_message: ^0.0.13+1
  google_generative_ai: ^0.4.7
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  http: ^1.6.0
  material_ui: ^0.0.1
  pull_down_button: ^0.10.2
  uuid: ^4.5.2
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/flyer_example/pattern.png
