name: friend_app
description: "Friend cross-platform social app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  image: ^4.5.2
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  share_plus: ^10.1.4
  tinode: ^1.0.0-alpha.4
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite: ^2.4.2
  flutter_chat_core: ^2.9.1
  flutter_chat_ui: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
