import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:tdesign_flutter_icons/tdesign_flutter_icons.dart';

import 'package:shared_preferences/shared_preferences.dart';
import 'package:image/image.dart' as img;
import 'package:image_picker/image_picker.dart';
import 'package:geolocator/geolocator.dart';
import 'package:geocoding/geocoding.dart';
import 'package:video_player/video_player.dart';
import 'package:video_thumbnail/video_thumbnail.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:path_provider/path_provider.dart';
import 'package:record/record.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:http/http.dart' as http;

import 'auth_client.dart';
import 'avatar_crop_page.dart';
import 'post_service.dart';
import 'discover_feed.dart';
import 'im_socket.dart';
import 'im_local_store.dart';

part 'im_new_chat.dart';
part 'shared_core.dart';
part 'figma_icon.dart';
part 'shared_clippers.dart';
part 'shared_models.dart';
part 'home_page.dart';
part 'create_post_page.dart';
part 'notifications_page.dart';
part 'other_profile_page.dart';
part 'my_profile_page.dart';
part 'my_profile_main.dart';
part 'profile_relations.dart';
part 'voice_record_page.dart';
part 'profile_widgets.dart';
part 'voice_pages.dart';
part 'companion_pages.dart';
part 'companion_profile_page.dart';
part 'voice_room_page.dart';
part 'voice_room_widgets.dart';
part 'voice_room_main.dart';
part 'fate_match_page.dart';
part 'aux_pages.dart';
part 'edit_profile_page.dart';
part 'settings_pages.dart';
part 'recommendation_pages.dart';
part 'detail_support_pages.dart';
part 'app_startup_pages.dart';
part 'app_bootstrap.dart';
part 'auth_entry_pages.dart';
part 'password_login_page.dart';
part 'register_page.dart';
part 'reset_password_page.dart';
part 'filled_login_page.dart';
part 'verification_page.dart';
part 'phone_register_page.dart';
part 'email_register_page.dart';
part 'password_setup_page.dart';
part 'profile_setup_page.dart';
part 'auth_scaffold.dart';
part 'auth_field.dart';
part 'primary_auth_button.dart';
part 'shell_page.dart';
part 'post_card.dart';
part 'media_components.dart';
part 'home_components.dart';
part 'detail_widgets.dart';
part 'create_post_state.dart';
part 'qr_code_page.dart';
part 'discover_page.dart';
part 'dynamic_detail_page.dart';

void main() => runApp(const DDApp());
